name: Test

on: [push, pull_request]


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.14, 1.15]
        os: [ubuntu-18.04, ubuntu-16.04, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set up golang ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ matrix.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ matrix.os }}-go-${{ matrix.go-version }}-

      - name: Run Tests
        shell: bash
        run: make test
